### ISSUE TITLE
StopIteration error

### ISSUE THREAD

**Issue by SeekPoint** [StonyBrookNLP/event-tensors#3]
ub16hp@UB16HP:~/ub16_prj/event-tensors$ python3.5 train_event_prediction.py 
(128, 10)
(128, 10)
(128, 10)
(128, 10)
(128, 10)
(128, 10)
2018-12-02 16:14:25.420912: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-02 16:14:25.567080: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-02 16:14:25.567427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.12GiB
2018-12-02 16:14:25.567462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Starting Fresh
Average Loss on 50 is 0.10399557366967202
Average Loss on 100 is 0.1009260854125023
Average Loss on 150 is 0.09745909363031385
Average Loss on 200 is 0.09509332507848742
Average Loss on 250 is 0.09339955508708954
Average Loss on 300 is 0.09256721824407578
Average Loss on 350 is 0.09019083708524704
Average Loss on 400 is 0.08809589222073558
Average Loss on 450 is 0.08994308814406395
Average Loss on 500 is 0.08769825130701064
Traceback (most recent call last):
  File "train_event_prediction.py", line 446, in <module>
    train_prediction_network(instances, embeddings)
  File "train_event_prediction.py", line 398, in train_prediction_network
    feed_dict, done = fill_feed_dict(inst_iter, input_ph, target_ph, neg_ph, embeddings)
  File "train_event_prediction.py", line 99, in fill_feed_dict
    inst = next(instance_iter)
  File "/home/ub16hp/ub16_prj/event-tensors/utils/train_utils.py", line 73, in __iter__
    filled = self.fill_queue()
  File "/home/ub16hp/ub16_prj/event-tensors/utils/train_utils.py", line 218, in fill_queue
    neg_inst = next(self.neg_instances)[1]
StopIteration
ub16hp@UB16HP:~/ub16_prj/event-tensors$

**Comment by StudentWorker** [comment]
I got the same question,are you solve it ???
